package com.bingo.riding.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.bingo.riding.dao.Conversation;
import com.bingo.riding.dao.ChatMessage;
import com.bingo.riding.dao.User;

import com.bingo.riding.dao.ConversationDao;
import com.bingo.riding.dao.ChatMessageDao;
import com.bingo.riding.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig conversationDaoConfig;
    private final DaoConfig chatMessageDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ConversationDao conversationDao;
    private final ChatMessageDao chatMessageDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        chatMessageDaoConfig = daoConfigMap.get(ChatMessageDao.class).clone();
        chatMessageDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        conversationDao = new ConversationDao(conversationDaoConfig, this);
        chatMessageDao = new ChatMessageDao(chatMessageDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Conversation.class, conversationDao);
        registerDao(ChatMessage.class, chatMessageDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        conversationDaoConfig.getIdentityScope().clear();
        chatMessageDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

    public ChatMessageDao getChatMessageDao() {
        return chatMessageDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
