package com.bingo.riding.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.bingo.riding.dao.ChatMessage;
import com.bingo.riding.dao.Conversation;

import com.bingo.riding.dao.ChatMessageDao;
import com.bingo.riding.dao.ConversationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatMessageDaoConfig;
    private final DaoConfig conversationDaoConfig;

    private final ChatMessageDao chatMessageDao;
    private final ConversationDao conversationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatMessageDaoConfig = daoConfigMap.get(ChatMessageDao.class).clone();
        chatMessageDaoConfig.initIdentityScope(type);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        chatMessageDao = new ChatMessageDao(chatMessageDaoConfig, this);
        conversationDao = new ConversationDao(conversationDaoConfig, this);

        registerDao(ChatMessage.class, chatMessageDao);
        registerDao(Conversation.class, conversationDao);
    }
    
    public void clear() {
        chatMessageDaoConfig.getIdentityScope().clear();
        conversationDaoConfig.getIdentityScope().clear();
    }

    public ChatMessageDao getChatMessageDao() {
        return chatMessageDao;
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

}
